name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/Image1.svg
    - assets/images/Frame.svg
    - assets/images/Frame4.svg
    - assets/images/NavigateLeft.svg
    - assets/images/Facebook.svg
    - assets/images/Google.svg
    - assets/images/WelcomeImage.png
    - assets/images/logo2.svg
    - assets/images/UnionFrame.svg
    - assets/images/Widget1.svg
    - assets/images/Widget2.svg
    - assets/images/Widget3.svg
    - assets/images/Widget4.svg
    - assets/images/Widget5.svg
    - assets/images/Widget6.svg
    - assets/images/apple.svg
    - assets/images/woman.svg
    - assets/images/dailyframe1.svg
    - assets/images/dailyframe2.svg
    - assets/images/dailyframe3.svg
    - assets/images/image20.svg
    - assets/images/image21.svg
    - assets/images/homeIcon.svg
    - assets/images/sleepIcon.svg
    - assets/images/meditateIcon.svg
    - assets/images/musicIcon.svg
    - assets/images/profileIcon.svg
    - assets/images/container1.svg
    - assets/images/container2.svg
    - assets/images/sun.svg
    - assets/images/heart.svg
    - assets/images/download.svg
    - assets/images/heartIcon.svg
    - assets/images/headphoneIcon.svg
    - assets/images/all.svg
    - assets/images/anxious.svg
    - assets/images/kids.svg
    - assets/images/my.svg
    - assets/images/sleep.svg
    - assets/images/frame105.svg
    - assets/images/frame106.svg
    - assets/images/frame107.svg
    - assets/images/calm.svg
    - assets/images/anxiet.svg
    - assets/images/backframe1.svg
    - assets/images/backframe2.svg
    - assets/images/backframe3.svg
    - assets/images/backframe4.svg
    - assets/images/removeIcon.svg
    - assets/images/navigaterightTime.svg
    - assets/images/navigateleftTime.svg
    - assets/images/home105.svg
    - assets/images/sleepframe.svg
    - assets/images/cloud.svg
    - assets/images/birds.svg

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400

    - family: HelveticaNeueRegular
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Rg.ttf
          weight: 400

    - family: HelveticaNeueBold
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Bd.otf
          weight: 700
