name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/Image1.svg
    - assets/images/Frame.svg
    - assets/images/Frame4.svg
    - assets/images/NavigateLeft.svg
    - assets/images/Facebook.svg
    - assets/images/Google.svg
    - assets/images/WelcomeImage.png
    - assets/images/logo2.svg
    - assets/images/UnionFrame.svg
    - assets/images/Widget1.svg
    - assets/images/Widget2.svg
    - assets/images/Widget3.svg
    - assets/images/Widget4.svg
    - assets/images/Widget5.svg
    - assets/images/Widget6.svg

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400

    - family: HelveticaNeueRegular
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Rg.ttf
          weight: 400

    - family: HelveticaNeueBold
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Bd.otf
          weight: 700
